### ISSUE TITLE
Mod auto-download (MAD) tracker

### ISSUE THREAD

**Issue by Alystrasz** [R2Northstar/Northstar#674]
While there is some progress on the feature, multiple bugs must be fixed before it can be publicly released.

##### Issues

- [ ] Fetch manifesto when trying to download a mod (and not before)
    - [ ] **Launcher PR:** https://github.com/R2Northstar/NorthstarLauncher/pull/751
    - [ ] **Mods PR:** https://github.com/R2Northstar/NorthstarMods/pull/821
- [ ] Make client able to deal with multiple mod versions
- [ ] https://github.com/R2Northstar/NorthstarLauncher/issues/756
